### ISSUE TITLE
Current versions of heavyai and cudf don't work together

### ISSUE THREAD

**Issue by randerzander** [heavyai/heavyai#38]
It looks like the current version of heavyai is out of date w/ cudf's API.

After starting the heavyai Docker image, registering my license key as directed, and creating a conda environment as directed by the docs:
```
conda create -n heavyai-gpu -c rapidsai -c nvidia -c conda-forge -c defaults python cudf cudatoolkit heavyai
...
conda list | grep rapids
cubinlinker               0.2.2            py39h11215e4_0    rapidsai
cudf                      22.12.01        cuda_11_py39_gf700408e68_0    rapidsai
libcudf                   22.12.01        cuda11_gf700408e68_0    rapidsai
librmm                    22.12.00        cuda11_g8aae42d1_0    rapidsai
rmm                       22.12.00        cuda11_py39_g8aae42d1_0    rapidsai
...
heavyai                   1.0                pyhd8ed1ab_0    conda-forge
pyheavydb                 6.1.1              pyhb39878e_1    conda-forge
``` 

Then trying to connect
```
>>> from heavyai import connect
>>> con = connect(user="admin", password="HyperInteractive", host="localhost",
...               dbname="heavyai")
>>> con
Connection(heavydb://admin:***@localhost:6274/heavyai?protocol=binary)
>>> con.select_ipc_gpu("show tables")
Traceback (most recent call last):
  File "/home/nfs/rgelhausen/conda/envs/heavyai-gpu/lib/python3.9/site-packages/heavyai/connection.py", line 317, in select_ipc_gpu
    from cudf.comm.gpuarrow import GpuArrowReader  # noqa
ModuleNotFoundError: No module named 'cudf.comm.gpuarrow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/rgelhausen/conda/envs/heavyai-gpu/lib/python3.9/site-packages/heavyai/connection.py", line 320, in select_ipc_gpu
    raise ImportError(
ImportError: The 'cudf' package is required for `select_ipc_gpu`
```

**Comment by randerzander** [comment]
After backing up to the cudf=22.06 release, I can get a bit further, but then hit issues querying the included demo tables:
```
conda create -n heavyai-gpu -c rapidsai -c nvidia -c conda-forge -c defaults python cudf=22.06 cudatoolkit heavyai
```

Test:
```
>>> con.get_tables()
['heavyai_us_states', 'heavyai_us_counties', 'heavyai_countries']
>>> con.select_ipc_gpu("select count(*) from heavyai_us_states")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/rgelhausen/conda/envs/heavyai-gpu/lib/python3.9/site-packages/heavyai/connection.py", line 336, in select_ipc_gpu
    df = _parse_tdf_gpu(tdf)
  File "/home/nfs/rgelhausen/conda/envs/heavyai-gpu/lib/python3.9/site-packages/heavyai/_utils.py", line 113, in _parse_tdf_gpu
    schema_buffer, shm_ptr = load_buffer(tdf.sm_handle, tdf.sm_size)
  File "/home/nfs/rgelhausen/conda/envs/heavyai-gpu/lib/python3.9/site-packages/heavyai/ipc.py", line 48, in load_buffer
    raise ValueError("Invalid shared memory key {}".format(shmkey))
ValueError: Invalid shared memory key 1804289383
```

**Comment by pearu** [comment]
https://github.com/heavyai/heavyai/pull/39 fixes this in the next heavyai release.
